//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iJob2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Request
    {
        public int Job_Request_ID { get; set; }
        public string Client_ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Category { get; set; }
        public string Job_Specifications { get; set; }
        public string Location { get; set; }
        public bool Transport_Status { get; set; }
        public decimal Cost { get; set; }
        public Nullable<bool> Assigned_Status { get; set; }
    }
}
